<a href="https://colab.research.google.com/github/talhanoor23/generative-ai/blob/main/NLP/NLP_Master_Practice_(Imp)_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Text_Preprocessing**

In [ ]:
paragraph ="""
Imran Ahmed Khan Niazi[a] (born 5 October 1952) is a Pakistani politician and former cricketer who served as the 19th prime minister of Pakistan from August 2018 until April 2022. He is the founder and former chairman of the political party Pakistan Tehreek-e-Insaf (PTI) from 1996 to 2023. He was the captain of the Pakistan national cricket team throughout the 1980s and early 1990s.

Born in Lahore, Khan graduated from Keble College, Oxford. He began his international cricket career in a 1971 Test series against England. Khan played until 1992, served as the team's captain intermittently between 1982 and 1992, and won the 1992 Cricket World Cup, Pakistan's only victory in the competition. Considered one of cricket's greatest all-rounders, Khan was later inducted into the ICC Cricket Hall of Fame.

Founding the Pakistan Tehreek-e-Insaf (PTI) in 1996, Khan won a seat in the National Assembly from his hometown of Mianwali, in the 2002 general election. PTI became the second-largest party by popular vote in the 2013 election, and five years later, running on a populist platform, PTI formed a coalition government with independents with Khan as prime minister. Khan's government inherited a balance of payments crisis and sought bailouts from the IMF; he presided over GDP growth after initial contraction, implemented austerity policies and increased tax collection. His government committed to a renewable energy transition, launched the Ehsaas Programme, and the Plant for Pakistan initiative, and expanded the protected areas of Pakistan and Sehat Sahulat Program. He presided over the COVID-19 pandemic, which caused economic turmoil and rising inflation in the country. In April 2022, during a constitutional crisis following the Lettergate affair, Khan became the first Pakistani prime minister to be removed from office through a no-confidence motion.

In October that year, on account of the Toshakhana reference case, Khan was disqualified by the Election Commission of Pakistan from taking office for one term of the National Assembly of Pakistan. In November, he survived an assassination attempt during a political rally in Wazirabad. In May 2023, Khan was arrested on corruption charges at the Islamabad High Court by paramilitary troops. Protests broke out throughout Pakistan, some of which escalated into violent riots. Khan was sentenced to a three-year jail term in August 2023 after being found guilty of misusing his premiership to buy and sell gifts in state possession. He was subsequently sentenced to ten years in prison in early 2024 for leaking state secrets and violating the Official Secrets Act in the Lettergate affair, and an additional seven years for breaching Islamic marriage laws with his wife; both of these sentences were overturned in mid-2024. Khan has since been charged on matters related to the 2023 riots, clashes between his supporters and police in September 2024 and in the Al-Qadir Trust case in January 2025, receiving a 14-year sentence.
"""

In [ ]:
paragraph

"\nImran Ahmed Khan Niazi[a] (born 5 October 1952) is a Pakistani politician and former cricketer who served as the 19th prime minister of Pakistan from August 2018 until April 2022. He is the founder and former chairman of the political party Pakistan Tehreek-e-Insaf (PTI) from 1996 to 2023. He was the captain of the Pakistan national cricket team throughout the 1980s and early 1990s.\n\nBorn in Lahore, Khan graduated from Keble College, Oxford. He began his international cricket career in a 1971 Test series against England. Khan played until 1992, served as the team's captain intermittently between 1982 and 1992, and won the 1992 Cricket World Cup, Pakistan's only victory in the competition. Considered one of cricket's greatest all-rounders, Khan was later inducted into the ICC Cricket Hall of Fame.\n\nFounding the Pakistan Tehreek-e-Insaf (PTI) in 1996, Khan won a seat in the National Assembly from his hometown of Mianwali, in the 2002 general election. PTI became the second-largest

In [ ]:
import nltk

In [ ]:
# from nltk.stem import WordNetLemmatizer
# lemmatizer = WordNetLemmatizer()

In [ ]:
# Download the 'punkt_tab' resource
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# Now you can use sent_tokenize
sentences = nltk.sent_tokenize(paragraph)

In [ ]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [ ]:
sentences

['\nImran Ahmed Khan Niazi[a] (born 5 October 1952) is a Pakistani politician and former cricketer who served as the 19th prime minister of Pakistan from August 2018 until April 2022.',
 'He is the founder and former chairman of the political party Pakistan Tehreek-e-Insaf (PTI) from 1996 to 2023.',
 'He was the captain of the Pakistan national cricket team throughout the 1980s and early 1990s.',
 'Born in Lahore, Khan graduated from Keble College, Oxford.',
 'He began his international cricket career in a 1971 Test series against England.',
 "Khan played until 1992, served as the team's captain intermittently between 1982 and 1992, and won the 1992 Cricket World Cup, Pakistan's only victory in the competition.",
 "Considered one of cricket's greatest all-rounders, Khan was later inducted into the ICC Cricket Hall of Fame.",
 'Founding the Pakistan Tehreek-e-Insaf (PTI) in 1996, Khan won a seat in the National Assembly from his hometown of Mianwali, in the 2002 general election.',
 'PT

In [ ]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [ ]:
stemmer.stem('goes')

'goe'

In [ ]:
lemmatizer.lemmatize('history')

'history'

In [ ]:
import re

In [ ]:
corpus = []
for i in range(len(sentences)):
    words = re.sub('[^a-zA-Z]',' ',sentences[i])
    words = words.lower()
    corpus.append(words)
# corpus = []
# for i in range(len(sentences)):
#     words = re.sub('[^a-zA-Z]',' ',sentences[i])
#     words = words.lower()
#     words = words.split()
#     words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
#     words = ' '.join(words)
#     corpus.append(words)

In [ ]:
corpus

[' imran ahmed khan niazi a   born   october       is a pakistani politician and former cricketer who served as the   th prime minister of pakistan from august      until april      ',
 'he is the founder and former chairman of the political party pakistan tehreek e insaf  pti  from      to      ',
 'he was the captain of the pakistan national cricket team throughout the     s and early     s ',
 'born in lahore  khan graduated from keble college  oxford ',
 'he began his international cricket career in a      test series against england ',
 'khan played until       served as the team s captain intermittently between      and       and won the      cricket world cup  pakistan s only victory in the competition ',
 'considered one of cricket s greatest all rounders  khan was later inducted into the icc cricket hall of fame ',
 'founding the pakistan tehreek e insaf  pti  in       khan won a seat in the national assembly from his hometown of mianwali  in the      general election ',
 'pti

In [ ]:
for i in corpus:
    words = word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

In [ ]:
for i in corpus:
    words = word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

In [ ]:
corpus_2 = []
for i in range(len(sentences)):
    words = re.sub('[^a-zA-Z]',' ',sentences[i])
    words = words.lower()
    words = words.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    words = ' '.join(words)
    corpus_2.append(words)

In [ ]:
corpus_2

['imran ahmed khan niazi born october pakistani politician former cricketer served th prime minister pakistan august april',
 'founder former chairman political party pakistan tehreek e insaf pti',
 'captain pakistan national cricket team throughout early',
 'born lahore khan graduated keble college oxford',
 'began international cricket career test series england',
 'khan played served team captain intermittently cricket world cup pakistan victory competition',
 'considered one cricket greatest rounder khan later inducted icc cricket hall fame',
 'founding pakistan tehreek e insaf pti khan seat national assembly hometown mianwali general election',
 'pti became second largest party popular vote election five year later running populist platform pti formed coalition government independent khan prime minister',
 'khan government inherited balance payment crisis sought bailouts imf presided gdp growth initial contraction implemented austerity policy increased tax collection',
 'governmen

# **Count_Vectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True) #ngram_range=(2,2)

In [ ]:
X = cv.fit_transform(corpus_2) #.toarray()

In [ ]:
cv.vocabulary_

{'imran': 80,
 'ahmed': 4,
 'khan': 96,
 'niazi': 113,
 'born': 18,
 'october': 115,
 'pakistani': 122,
 'politician': 133,
 'former': 62,
 'cricketer': 45,
 'served': 167,
 'th': 182,
 'prime': 139,
 'minister': 109,
 'pakistan': 121,
 'august': 12,
 'april': 6,
 'founder': 64,
 'chairman': 26,
 'political': 132,
 'party': 125,
 'tehreek': 178,
 'insaf': 88,
 'pti': 145,
 'captain': 22,
 'national': 112,
 'cricket': 44,
 'team': 177,
 'throughout': 184,
 'early': 49,
 'lahore': 97,
 'graduated': 70,
 'keble': 95,
 'college': 32,
 'oxford': 120,
 'began': 17,
 'international': 90,
 'career': 23,
 'test': 181,
 'series': 166,
 'england': 54,
 'played': 129,
 'intermittently': 89,
 'world': 196,
 'cup': 47,
 'victory': 190,
 'competition': 35,
 'considered': 37,
 'one': 118,
 'greatest': 71,
 'rounder': 155,
 'later': 99,
 'inducted': 83,
 'icc': 77,
 'hall': 74,
 'fame': 57,
 'founding': 65,
 'seat': 158,
 'assembly': 10,
 'hometown': 76,
 'mianwali': 107,
 'general': 67,
 'election': 5

In [ ]:
X[1].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [ ]:
X.shape

(20, 198)

# TF-IDF **Vectorizer**

In [ ]:
corpus_2

['imran ahmed khan niazi born october pakistani politician former cricketer served th prime minister pakistan august april',
 'founder former chairman political party pakistan tehreek e insaf pti',
 'captain pakistan national cricket team throughout early',
 'born lahore khan graduated keble college oxford',
 'began international cricket career test series england',
 'khan played served team captain intermittently cricket world cup pakistan victory competition',
 'considered one cricket greatest rounder khan later inducted icc cricket hall fame',
 'founding pakistan tehreek e insaf pti khan seat national assembly hometown mianwali general election',
 'pti became second largest party popular vote election five year later running populist platform pti formed coalition government independent khan prime minister',
 'khan government inherited balance payment crisis sought bailouts imf presided gdp growth initial contraction implemented austerity policy increased tax collection',
 'governmen

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer() #ngram_range=(2,3), max_features = .. used to get top vectors with high frequency

In [ ]:
y = tf.fit_transform(corpus_2).toarray()

In [ ]:
y.shape

(20, 198)

In [ ]:
y[0]

array([0.        , 0.        , 0.        , 0.        , 0.27559962,
       0.        , 0.24225628, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.24225628, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.24225628, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27559962, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.24225628, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# **Cosine_Similarity**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(y)

In [ ]:
similarity[0].shape

(20,)

In [ ]:
similarity

array([[1.        , 0.11380331, 0.03924877, 0.10916015, 0.        ,
        0.11462506, 0.01630612, 0.04412351, 0.09188424, 0.01253309,
        0.0408045 , 0.        , 0.23042558, 0.11705005, 0.        ,
        0.01771461, 0.03462258, 0.07194664, 0.        , 0.01344387],
       [0.11380331, 1.        , 0.0546275 , 0.        , 0.        ,
        0.03812497, 0.        , 0.30516738, 0.17873346, 0.        ,
        0.05679281, 0.        , 0.        , 0.06284497, 0.11388772,
        0.        , 0.04818865, 0.        , 0.        , 0.        ],
       [0.03924877, 0.0546275 , 1.        , 0.        , 0.09685314,
        0.36448961, 0.15023702, 0.14037906, 0.        , 0.        ,
        0.06939835, 0.        , 0.        , 0.15630111, 0.        ,
        0.        , 0.20863404, 0.        , 0.07042943, 0.        ],
       [0.10916015, 0.        , 0.        , 1.        , 0.        ,
        0.02610031, 0.02421994, 0.02561237, 0.01830529, 0.01861576,
        0.        , 0.        , 0.02224725, 0

In [ ]:
import pandas as pd

# Create a DataFrame for better visualization
df = pd.DataFrame(similarity, index=[f'Doc_{i}' for i in range(len(corpus_2))],
                             columns=[f'Doc_{i}' for i in range(len(corpus_2))])


In [ ]:
df

,Doc_0,Doc_1,Doc_2,Doc_3,Doc_4,Doc_5,Doc_6,Doc_7,Doc_8,Doc_9,Doc_10,Doc_11,Doc_12,Doc_13,Doc_14,Doc_15,Doc_16,Doc_17,Doc_18,Doc_19
Doc_0,1.000000,0.113803,0.039249,0.109160,0.000000,0.114625,0.016306,0.044124,0.091884,0.012533,0.040805,0.000000,0.230426,0.117050,0.000000,0.017715,0.034623,0.071947,0.000000,0.013444
Doc_1,0.113803,1.000000,0.054628,0.000000,0.000000,0.038125,0.000000,0.305167,0.178733,0.000000,0.056793,0.000000,0.000000,0.062845,0.113888,0.000000,0.048189,0.000000,0.000000,0.000000
Doc_2,0.039249,0.054628,1.000000,0.000000,0.096853,0.364490,0.150237,0.140379,0.000000,0.000000,0.069398,0.000000,0.000000,0.156301,0.000000,0.000000,0.208634,0.000000,0.070429,0.000000
Doc_3,0.109160,0.000000,0.000000,1.000000,0.000000,0.026100,0.024220,0.025612,0.018305,0.018616,0.000000,0.000000,0.022247,0.021512,0.000000,0.026312,0.000000,0.021527,0.000000,0.019969
Doc_4,0.000000,0.000000,0.096853,0.000000,1.000000,0.067595,0.125450,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc_5,0.114625,0.038125,0.364490,0.026100,0.067595,1.000000,0.124206,0.052373,0.014628,0.014876,0.048434,0.000000,0.017778,0.070786,0.000000,0.021027,0.041096,0.017203,0.000000,0.015957
Doc_6,0.016306,0.000000,0.150237,0.024220,0.125450,0.124206,1.000000,0.018993,0.067387,0.013805,0.000000,0.000000,0.016498,0.079192,0.000000,0.019512,0.000000,0.015963,0.000000,0.014808
Doc_7,0.044124,0.305167,0.140379,0.025612,0.000000,0.052373,0.018993,1.000000,0.153360,0.014598,0.047528,0.000000,0.017446,0.245240,0.000000,0.020634,0.040328,0.016881,0.000000,0.015659
Doc_8,0.091884,0.178733,0.000000,0.018305,0.000000,0.014628,0.067387,0.153360,1.000000,0.044111,0.035169,0.000000,0.142393,0.078923,0.000000,0.014747,0.000000,0.040034,0.040319,0.037137
Doc_9,0.012533,0.000000,0.000000,0.018616,0.000000,0.014876,0.013805,0.014598,0.044111,1.000000,0.035765,0.060867,0.062949,0.012261,0.000000,0.014997,0.000000,0.012270,0.000000,0.011381


# **Similarity_Recommendor_System**

In [ ]:
# Function to get top similar documents for a given document
def get_top_similar_docs(doc_index, top_n=3):
    similarity_scores = list(enumerate(similarity[doc_index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # Skip the first one (self-similarity)
    top_similar = similarity_scores[1:top_n+1]

    return [(f'Doc_{i}', score) for i, score in top_similar]

In [ ]:
similar_docs = get_top_similar_docs(0)
print(similar_docs)

[('Doc_12', 0.2304255806355678), ('Doc_13', 0.1170500460787066), ('Doc_5', 0.11462506278571673)]


In [ ]:
similar_docs = get_top_similar_docs(5)
print(similar_docs)

[('Doc_2', 0.36448961242286576), ('Doc_6', 0.12420648011894045), ('Doc_0', 0.11462506278571673)]
